<?php

namespace FORUM\ForumBundle\Repository;

/**
 * threadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class threadRepository extends \Doctrine\ORM\EntityRepository
{
}
